name: ollama
version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    # Uncomment below for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu

    # Uncomment below to expose Ollama API outside the container stack
    # ports:
    #   - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    tty: true

  nginx:
    image: nginx:latest
    container_name: ollama_nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./apikeys.conf:/etc/nginx/apikeys.conf
    ports:
      - 5050:5050

volumes:
  ollama_data:
